services:
  spark-master:
    build: .
    image: spark-custom:3.4.2
    container_name: spark-master
    command: >
      bash -c "
      /opt/spark/sbin/start-master.sh &&
      tail -f /opt/spark/logs/*
      "
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ../:/opt/project
      - ../logs/spark-events:/opt/spark/events
      - ./spark/conf:/opt/spark/conf

  spark-worker:
    build: .
    image: spark-custom:3.4.2
    container_name: spark-worker
    command: >
      bash -c "
      /opt/spark/sbin/start-worker.sh spark://spark-master:7077 &&
      tail -f /opt/spark/logs/*
      "
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ../:/opt/project
      - ../logs/spark-events:/opt/spark/events
      - ./spark/conf:/opt/spark/conf

  spark-history-server:
    build: .
    image: spark-custom:3.4.2
    container_name: spark-history
    command: >
      bash -c "
      /opt/spark/sbin/start-history-server.sh &&
      tail -f /opt/spark/logs/*
      "
    ports:
      - "18080:18080"
    volumes:
      - ../logs/spark-events:/opt/spark/events
      - ./spark/conf:/opt/spark/conf
